
services:
  # database
  db:
    image: postgres:15-alpine
    restart: always
    container_name: ocr_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  ocr_service:
    build:
      context: .
      dockerfile: ./ocr_service.Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ocr_db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ocr_redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - db
      - redis
      - ocr_worker
    ports:
      - ${OCR_SERVICE_PORT}:8000

  ocr_worker:
    build:
      context: .
      dockerfile: ./ocr_worker.Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ocr_db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ocr_redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - db
      - redis
    ports:
      - ${OCR_WORKER_PORT}:8000

  redis:
    image: redis:alpine
    container_name: ocr_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
  
  ocr_frontend:
    build:
      context: .
      dockerfile: ./ocr_frontend.Dockerfile
    environment:
      VITE_BACKEND_URL: http://${OCR_SERVICE_HOST}:${OCR_SERVICE_PORT}
    ports:
      - ${OCR_FRONTEND_PORT}:5173
    depends_on:
      - ocr_service

volumes:
  db_data:
  redis_data:
